version: '3.7'
services:
  client:
    build: 
      context: ./client
      dockerfile: Dockerfile
    volumes:
      - './client:/app'
      - '/app/node_modules'
    ports:
      - '3000:3000'
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - server

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    volumes:
      - './server:/app'
      - '/app/node_modules'
    ports:
      - '5000:5000'

